### ISSUE TITLE
Question about Disentangle Layers in Autoencoder

### ISSUE THREAD

**Issue by Yuki-zik** [csjunjun/DifAttack#2]
### Description:

I have a question regarding the architecture of the autoencoder, specifically about the Disentangle layers.

### Issues:

1. Why are there two Disentangle layers needed in the network?
2. Why are the internal adversarial features from the first Disentangle layer used in the visual convolution layer of the second Disentangle layer?

**Comment by csjunjun** [comment]
Thank you for your attention on our work.
1. These two Disentangle layers are used for extracting the adversarial feature and visual feature respectively.
2. We adopt a hierarchical disentangling structure and assume that there are still a small number of visually relevant features remaining in the adversarial features obtained after the first disentangle layer. So in the second visual disentangle layer, we again extract the residual visual features from the adversarial features obtained through the first disentangle layer. Then merge these visual features to obtain the final visual feature. 

Overall, the two hierarchical disentangling layers are used for extract more subtle disentangled features.

**Comment by Yuki-zik** [comment]
Thank you for your detailed explanation, which has resolved many of my doubts. I have a new question: how are the skip connections set up in your network? And on what basis is the position of the skip connections determined?

**Comment by csjunjun** [comment]
This is a network structure similar to a famous work called UNet, refer to this [link](https://github.com/milesial/Pytorch-UNet/tree/master). The position of the skip connections is determined by the size of output features obtained from the encoder and the size of input feature of the decoder. These two sizes need to be a match.

**Comment by Yuki-zik** [comment]
thanks for your reply
